import { createClient } from "npm:@supabase/supabase-js@2";
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const BASES={production:"https://api.cieloecommerce.cielo.com.br",sandbox:"https://apisandbox.cieloecommerce.cielo.com.br"} as const;
function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{...CORS,"Content-Type":"application/json"}})}
function cents(v:number){return Math.round(Number(v)*100)}
type Body={order_id:string;amount?:number;reason?:string;idempotency_key?:string;mode?:"execute"|"request"};

Deno.serve(async(req)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});
 try{
  const U=Deno.env.get("SUPABASE_URL")!,A=Deno.env.get("SUPABASE_ANON_KEY")!,S=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
  const authHeader=req.headers.get("Authorization"); if(!authHeader?.startsWith("Bearer "))return json({error:"Unauthorized"},401);
  const uc=createClient(U,A,{global:{headers:{Authorization:authHeader}}}); const{data:claims,error:cErr}=await uc.auth.getClaims(authHeader.replace("Bearer ",""));
  if(cErr||!claims?.claims?.sub)return json({error:"Unauthorized"},401); const userId=claims.claims.sub as string;
  const admin=createClient(U,S);
  let MERCHANT_ID=(Deno.env.get("CIELO_MERCHANT_ID")||"").trim(),MERCHANT_KEY=(Deno.env.get("CIELO_MERCHANT_KEY")||"").trim();
  if(!MERCHANT_ID||!MERCHANT_KEY){const[a,b]=await Promise.all([admin.rpc("get_private_payment_secret",{p_name:"CIELO_MERCHANT_ID"}),admin.rpc("get_private_payment_secret",{p_name:"CIELO_MERCHANT_KEY"})]);MERCHANT_ID=MERCHANT_ID||String(a.data||"");MERCHANT_KEY=MERCHANT_KEY||String(b.data||"");}
  if(!MERCHANT_ID||!MERCHANT_KEY)return json({error:"Cielo não configurada"},500);
  let body:Body;try{body=await req.json()}catch{return json({error:"Body inválido"},400)}
  if(!body?.order_id)return json({error:"order_id obrigatório"},400);if(body.amount!==undefined&&(typeof body.amount!=="number"||body.amount<=0))return json({error:"amount deve ser > 0"},400);
  const{data:roles}=await admin.from("user_roles").select("role").eq("user_id",userId),isAdmin=(roles||[]).some((r:any)=>r.role==="admin"),isSeller=(roles||[]).some((r:any)=>r.role==="seller");if(!isAdmin&&!isSeller)return json({error:"Sem permissão"},403);
  let canExecute=isAdmin,canRequest=isAdmin;if(!isAdmin){const{data:p}=await admin.from("seller_permissions").select("*").eq("user_id",userId).maybeSingle();canRequest=!!p?.can_request_refund;canExecute=!!p?.can_execute_refund;}
  const{data:order,error:oErr}=await admin.from("orders").select("*").eq("id",body.order_id).maybeSingle();if(oErr||!order)return json({error:"Pedido não encontrado"},404);const paymentId=order.cielo_payment_id;if(!paymentId)return json({error:"Pedido sem ID de pagamento Cielo"},400);if(!["approved","partially_refunded"].includes(order.payment_status))return json({error:`Pedido não pode ser reembolsado (payment_status=${order.payment_status})`},400);
  const amount=body.amount,isTotal=amount===undefined,reqType=isTotal?"total":"partial",idemKey=body.idempotency_key||`${body.order_id}:${reqType}:${amount??"all"}:${Date.now()}`,wantsExecute=(body.mode||"execute")==="execute";
  const{data:rr,error:rrErr}=await admin.from("refund_requests").insert({order_id:order.id,payment_id:String(paymentId),requested_by:userId,reason:body.reason||null,type:reqType,amount:amount??order.total,status:"pending",idempotency_key:idemKey}).select().maybeSingle();if(rrErr){if(rrErr.code==="23505")return json({error:"Solicitação duplicada (idempotency_key)"},409);return json({error:rrErr.message},500);}
  if(!wantsExecute||!canExecute){if(!canRequest&&!canExecute){await admin.from("refund_requests").update({status:"denied",error_message:"Sem permissão"}).eq("id",rr!.id);return json({error:"Sem permissão para solicitar reembolso"},403);}await admin.from("orders").update({status:"reembolso_pendente"}).eq("id",order.id);await admin.from("order_events").insert({order_id:order.id,type:"refund_requested",message:`Reembolso ${reqType} solicitado`,created_by:userId,metadata:{refund_request_id:rr!.id,amount:amount??order.total}});await admin.from("admin_notifications").insert({type:"refund_requested",title:"Solicitação de reembolso",message:`Pedido ${order.id.slice(0,8)} — ${reqType} ${amount?"R$ "+amount.toFixed(2):"total"}`,order_id:order.id,role_target:"admin",priority:"high",metadata:{refund_request_id:rr!.id}});return json({ok:true,status:"pending",refund_request:rr});}
  await admin.from("refund_requests").update({status:"processing"}).eq("id",rr!.id);const{data:ps}=await admin.from("payment_settings").select("environment").eq("id",1).maybeSingle(),env=(ps as any)?.environment==="sandbox"?"sandbox":"production",base=BASES[env],url=isTotal?`${base}/1/sales/${paymentId}/void`:`${base}/1/sales/${paymentId}/void?amount=${cents(amount!)}`;
  const resp=await fetch(url,{method:"PUT",headers:{MerchantId:MERCHANT_ID,MerchantKey:MERCHANT_KEY,"Content-Type":"application/json"}}),rj=await resp.json().catch(()=>({}));
  if(!resp.ok){const msg=Array.isArray(rj)?rj.map((e:any)=>`${e.Code}: ${e.Message}`).join("; "):(rj?.Message||`HTTP ${resp.status}`);await admin.from("refund_requests").update({status:"failed",error_message:String(msg),processed_by:userId,processed_at:new Date().toISOString()}).eq("id",rr!.id);await admin.from("order_events").insert({order_id:order.id,type:"refund_failed",message:`Falha no reembolso Cielo: ${msg}`,created_by:userId,metadata:{refund_request_id:rr!.id}});return json({error:"Falha na Cielo",detail:msg},502);}
  const cieloRefundId=rj?.Tid?String(rj.Tid):String(paymentId);await admin.from("refund_requests").update({status:"completed",cielo_refund_id:cieloRefundId,processed_by:userId,processed_at:new Date().toISOString()}).eq("id",rr!.id);await admin.from("orders").update({payment_status:isTotal?"refunded":"partially_refunded",status:isTotal?"reembolsado":order.status,cielo_status:rj?.Status??order.cielo_status}).eq("id",order.id);await admin.from("order_events").insert({order_id:order.id,type:"refund_completed",message:`Reembolso ${reqType} concluído na Cielo${amount?` (R$ ${amount.toFixed(2)})`:""}`,created_by:userId,metadata:{refund_request_id:rr!.id,cielo_refund_id:cieloRefundId,amount:amount??order.total}});await admin.from("admin_notifications").insert({type:"refund_completed",title:"Reembolso concluído",message:`Pedido ${order.id.slice(0,8)} — ${reqType} ${amount?"R$ "+amount.toFixed(2):"total"}`,order_id:order.id,role_target:"admin",priority:"normal",metadata:{refund_request_id:rr!.id,cielo_refund_id:cieloRefundId}});return json({ok:true,status:"completed",refund_request_id:rr!.id,cielo_refund_id:cieloRefundId});
 }catch(e){return json({error:String((e as Error).message||e)},500);}
});
