import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { CheckCircle2, Layers3 } from "lucide-react";

export default function PlatformPlans(){
  const q=useQuery({queryKey:["platform-plans"],queryFn:async()=>{const db=supabase as any;const [plans,mods,links]=await Promise.all([db.from("saas_plans").select("*").eq("active",true).order("is_internal").order("name"),db.from("saas_modules").select("*").eq("active",true).order("sort_order"),db.from("saas_plan_modules").select("*").eq("enabled",true)]);const err=[plans,mods,links].find((x:any)=>x.error)?.error;if(err)throw err;return {plans:plans.data||[],mods:mods.data||[],links:links.data||[]};}});
  return <div className="p-6 lg:p-8 max-w-[1500px] mx-auto space-y-6"><div><p className="text-sm font-semibold text-slate-500">Comercial e produto</p><h1 className="text-3xl font-black mt-1">Planos e módulos</h1><p className="text-slate-600 mt-2">Estrutura dos pacotes do SaaS. Valores permanecem em aberto enquanto a política comercial não for definida.</p></div>{q.isLoading?<p>Carregando...</p>:<div className="grid gap-5 xl:grid-cols-2">{q.data?.plans.map((p:any)=>{const enabled=q.data!.links.filter((l:any)=>l.plan_id===p.id).map((l:any)=>l.module_code);return <Card key={p.id} className="rounded-2xl"><CardHeader><div className="flex items-center justify-between"><div><CardTitle className="flex items-center gap-2"><Layers3 className="h-5 w-5"/>{p.name}</CardTitle><p className="text-sm text-slate-500 mt-1">{p.description}</p></div>{p.is_internal&&<Badge>Interno</Badge>}</div></CardHeader><CardContent><div className="grid gap-2 md:grid-cols-2">{q.data!.mods.map((m:any)=><div key={m.code} className={`p-3 rounded-xl border text-sm flex gap-2 ${enabled.includes(m.code)?"bg-emerald-50 border-emerald-200":"opacity-40"}`}><CheckCircle2 className="h-4 w-4 mt-0.5 shrink-0"/><div><div className="font-semibold">{m.name}</div><div className="text-xs text-slate-500">{m.category}</div></div></div>)}</div><div className="mt-4 pt-4 border-t text-sm text-slate-500">Mensal: {p.monthly_price==null?"A definir":`R$ ${Number(p.monthly_price).toFixed(2)}`} · Anual: {p.yearly_price==null?"A definir":`R$ ${Number(p.yearly_price).toFixed(2)}`}</div></CardContent></Card>})}</div>}</div>;
}
