-- Restore the legacy Lovable business schema before importing client-zero data.
-- Generated from the validated 2026-07-18 PostgreSQL custom backup.
-- Idempotent on the legacy production database: existing columns are preserved.
begin;

ALTER TABLE public."admin_notifications" ADD COLUMN IF NOT EXISTS "type" text NOT NULL;
ALTER TABLE public."admin_notifications" ADD COLUMN IF NOT EXISTS "title" text NOT NULL;
ALTER TABLE public."admin_notifications" ADD COLUMN IF NOT EXISTS "message" text;
ALTER TABLE public."admin_notifications" ADD COLUMN IF NOT EXISTS "read" boolean DEFAULT false NOT NULL;
ALTER TABLE public."admin_notifications" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."admin_notifications" ADD COLUMN IF NOT EXISTS "priority" text DEFAULT 'normal'::text NOT NULL;
ALTER TABLE public."admin_notifications" ADD COLUMN IF NOT EXISTS "role_target" text DEFAULT 'admin'::text NOT NULL;
ALTER TABLE public."admin_notifications" ADD COLUMN IF NOT EXISTS "target_user_id" uuid;
ALTER TABLE public."admin_notifications" ADD COLUMN IF NOT EXISTS "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE public."admin_notifications" ADD COLUMN IF NOT EXISTS "read_at" timestamp with time zone;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "title" text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "subtitle" text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "image_url" text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "link" text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "position" integer DEFAULT 0 NOT NULL;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "cta_text" text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "mobile_image_url" text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "start_date" timestamp with time zone;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "end_date" timestamp with time zone;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "placement" text DEFAULT 'hero'::text NOT NULL;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "banner_type" text DEFAULT 'image'::text NOT NULL;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "published" boolean DEFAULT true NOT NULL;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "support_text" text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "legal_text" text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "discount_percent" integer;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "discount_prefix" text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "discount_suffix" text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "product_image_url" text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "background_image_url" text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "background_color" text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "accent_color" text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "button_color" text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "product_position" text DEFAULT 'right'::text NOT NULL;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "text_position" text DEFAULT 'left'::text NOT NULL;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "visual_style" text DEFAULT 'light'::text NOT NULL;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "linked_entity_type" text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "linked_entity_id" uuid;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "linked_entity_slug" text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "animation_type" text DEFAULT 'none'::text NOT NULL;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "show_text_over_image" boolean DEFAULT false NOT NULL;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "image_fit" text DEFAULT 'cover'::text NOT NULL;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "product_size" text DEFAULT 'large'::text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "show_side_shapes" boolean DEFAULT true;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "side_shapes_color" text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "title_font" text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "title_color" text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "support_color" text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "legal_color" text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "title_size" text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "background_intensity" text DEFAULT 'xsoft'::text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "side_shapes_size" text DEFAULT 'medium'::text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "visual_model" text DEFAULT 'auto'::text NOT NULL;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "size_variant" text DEFAULT 'hero-grande'::text NOT NULL;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "desktop_image_url" text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "tablet_image_url" text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "image_focus" text DEFAULT 'center'::text NOT NULL;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "image_alt" text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "badge" text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "highlight_price" numeric;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "secondary_image_url" text;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "autoplay_delay" integer DEFAULT 4000 NOT NULL;
ALTER TABLE public."banners" ADD COLUMN IF NOT EXISTS "transition_type" text DEFAULT 'slide'::text NOT NULL;
ALTER TABLE public."campaign_products" ADD COLUMN IF NOT EXISTS "position" integer DEFAULT 0 NOT NULL;
ALTER TABLE public."campaign_products" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."campaign_products" ADD COLUMN IF NOT EXISTS "featured_slot" smallint;
ALTER TABLE public."campaigns" ADD COLUMN IF NOT EXISTS "starts_at" timestamp with time zone;
ALTER TABLE public."campaigns" ADD COLUMN IF NOT EXISTS "ends_at" timestamp with time zone;
ALTER TABLE public."campaigns" ADD COLUMN IF NOT EXISTS "banner_image_url" text;
ALTER TABLE public."campaigns" ADD COLUMN IF NOT EXISTS "banner_link" text;
ALTER TABLE public."campaigns" ADD COLUMN IF NOT EXISTS "cta_text" text;
ALTER TABLE public."campaigns" ADD COLUMN IF NOT EXISTS "subtitle" text;
ALTER TABLE public."campaigns" ADD COLUMN IF NOT EXISTS "visual_style" text DEFAULT 'light'::text NOT NULL;
ALTER TABLE public."campaigns" ADD COLUMN IF NOT EXISTS "position" integer DEFAULT 0 NOT NULL;
ALTER TABLE public."campaigns" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."campaigns" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."campaigns" ADD COLUMN IF NOT EXISTS "banner_mode" text DEFAULT 'manual_url'::text NOT NULL;
ALTER TABLE public."campaigns" ADD COLUMN IF NOT EXISTS "banner_destination" text DEFAULT 'campaign'::text NOT NULL;
ALTER TABLE public."campaigns" ADD COLUMN IF NOT EXISTS "show_on_home" boolean DEFAULT false NOT NULL;
ALTER TABLE public."categories" ADD COLUMN IF NOT EXISTS "icon" text;
ALTER TABLE public."categories" ADD COLUMN IF NOT EXISTS "position" integer DEFAULT 0 NOT NULL;
ALTER TABLE public."categories" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."categories" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."categories" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE public."categories" ADD COLUMN IF NOT EXISTS "image_url" text;
ALTER TABLE public."categories" ADD COLUMN IF NOT EXISTS "show_in_menu" boolean DEFAULT true NOT NULL;
ALTER TABLE public."categories" ADD COLUMN IF NOT EXISTS "show_on_home" boolean DEFAULT true NOT NULL;
ALTER TABLE public."categories" ADD COLUMN IF NOT EXISTS "link" text;
ALTER TABLE public."categories" ADD COLUMN IF NOT EXISTS "band_color" text DEFAULT '#E11D2E'::text;
ALTER TABLE public."categories" ADD COLUMN IF NOT EXISTS "macro_group" text;
ALTER TABLE public."customer_addresses" ADD COLUMN IF NOT EXISTS "label" text;
ALTER TABLE public."customer_addresses" ADD COLUMN IF NOT EXISTS "number" text;
ALTER TABLE public."customer_addresses" ADD COLUMN IF NOT EXISTS "complement" text;
ALTER TABLE public."customer_addresses" ADD COLUMN IF NOT EXISTS "neighborhood" text;
ALTER TABLE public."customer_addresses" ADD COLUMN IF NOT EXISTS "reference" text;
ALTER TABLE public."customer_addresses" ADD COLUMN IF NOT EXISTS "is_default" boolean DEFAULT false NOT NULL;
ALTER TABLE public."customer_addresses" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."customer_addresses" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."customer_addresses" ADD COLUMN IF NOT EXISTS "lat" numeric;
ALTER TABLE public."customer_addresses" ADD COLUMN IF NOT EXISTS "lng" numeric;
ALTER TABLE public."customer_addresses" ADD COLUMN IF NOT EXISTS "place_id" text;
ALTER TABLE public."departments" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE public."departments" ADD COLUMN IF NOT EXISTS "image_url" text;
ALTER TABLE public."departments" ADD COLUMN IF NOT EXISTS "icon" text;
ALTER TABLE public."departments" ADD COLUMN IF NOT EXISTS "band_color" text;
ALTER TABLE public."departments" ADD COLUMN IF NOT EXISTS "position" integer DEFAULT 0 NOT NULL;
ALTER TABLE public."departments" ADD COLUMN IF NOT EXISTS "show_in_menu" boolean DEFAULT true NOT NULL;
ALTER TABLE public."departments" ADD COLUMN IF NOT EXISTS "show_on_home" boolean DEFAULT true NOT NULL;
ALTER TABLE public."departments" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."departments" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."home_layout" ADD COLUMN IF NOT EXISTS "label" text NOT NULL;
ALTER TABLE public."home_layout" ADD COLUMN IF NOT EXISTS "position" integer NOT NULL;
ALTER TABLE public."home_layout" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."home_layout" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."home_mosaic_tiles" ADD COLUMN IF NOT EXISTS "position" integer DEFAULT 0 NOT NULL;
ALTER TABLE public."home_mosaic_tiles" ADD COLUMN IF NOT EXISTS "size" text DEFAULT 'sm'::text NOT NULL;
ALTER TABLE public."home_mosaic_tiles" ADD COLUMN IF NOT EXISTS "title" text;
ALTER TABLE public."home_mosaic_tiles" ADD COLUMN IF NOT EXISTS "subtitle" text;
ALTER TABLE public."home_mosaic_tiles" ADD COLUMN IF NOT EXISTS "badge_text" text;
ALTER TABLE public."home_mosaic_tiles" ADD COLUMN IF NOT EXISTS "cta_text" text;
ALTER TABLE public."home_mosaic_tiles" ADD COLUMN IF NOT EXISTS "link" text;
ALTER TABLE public."home_mosaic_tiles" ADD COLUMN IF NOT EXISTS "image_url" text;
ALTER TABLE public."home_mosaic_tiles" ADD COLUMN IF NOT EXISTS "bg_style" text DEFAULT 'soft-pink'::text NOT NULL;
ALTER TABLE public."home_mosaic_tiles" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."home_mosaic_tiles" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."home_mosaic_tiles" ADD COLUMN IF NOT EXISTS "link_type" text DEFAULT 'manual'::text NOT NULL;
ALTER TABLE public."home_mosaic_tiles" ADD COLUMN IF NOT EXISTS "image_source" text DEFAULT 'auto'::text NOT NULL;
ALTER TABLE public."home_mosaic_tiles" ADD COLUMN IF NOT EXISTS "custom_image_url" text;
ALTER TABLE public."home_mosaic_tiles" ADD COLUMN IF NOT EXISTS "manual_link" text;
ALTER TABLE public."home_mosaic_tiles" ADD COLUMN IF NOT EXISTS "badge_preset" text;
ALTER TABLE public."menu_items" ADD COLUMN IF NOT EXISTS "menu_area" text NOT NULL;
ALTER TABLE public."menu_items" ADD COLUMN IF NOT EXISTS "label" text NOT NULL;
ALTER TABLE public."menu_items" ADD COLUMN IF NOT EXISTS "slug" text;
ALTER TABLE public."menu_items" ADD COLUMN IF NOT EXISTS "link_type" text DEFAULT 'manual'::text NOT NULL;
ALTER TABLE public."menu_items" ADD COLUMN IF NOT EXISTS "url" text;
ALTER TABLE public."menu_items" ADD COLUMN IF NOT EXISTS "page_key" text;
ALTER TABLE public."menu_items" ADD COLUMN IF NOT EXISTS "position" integer DEFAULT 0 NOT NULL;
ALTER TABLE public."menu_items" ADD COLUMN IF NOT EXISTS "show_on_desktop" boolean DEFAULT true NOT NULL;
ALTER TABLE public."menu_items" ADD COLUMN IF NOT EXISTS "show_on_mobile" boolean DEFAULT true NOT NULL;
ALTER TABLE public."menu_items" ADD COLUMN IF NOT EXISTS "open_in_new_tab" boolean DEFAULT false NOT NULL;
ALTER TABLE public."menu_items" ADD COLUMN IF NOT EXISTS "icon" text;
ALTER TABLE public."menu_items" ADD COLUMN IF NOT EXISTS "badge_text" text;
ALTER TABLE public."menu_items" ADD COLUMN IF NOT EXISTS "highlight" boolean DEFAULT false NOT NULL;
ALTER TABLE public."menu_items" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."menu_items" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."order_events" ADD COLUMN IF NOT EXISTS "type" text NOT NULL;
ALTER TABLE public."order_events" ADD COLUMN IF NOT EXISTS "old_status" text;
ALTER TABLE public."order_events" ADD COLUMN IF NOT EXISTS "new_status" text;
ALTER TABLE public."order_events" ADD COLUMN IF NOT EXISTS "message" text;
ALTER TABLE public."order_events" ADD COLUMN IF NOT EXISTS "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE public."order_events" ADD COLUMN IF NOT EXISTS "created_by" uuid;
ALTER TABLE public."order_events" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."order_items" ADD COLUMN IF NOT EXISTS "product_image_url" text;
ALTER TABLE public."order_items" ADD COLUMN IF NOT EXISTS "total" numeric;
ALTER TABLE public."order_items" ADD COLUMN IF NOT EXISTS "requires_prescription" boolean DEFAULT false NOT NULL;
ALTER TABLE public."order_items" ADD COLUMN IF NOT EXISTS "controlled" boolean DEFAULT false NOT NULL;
ALTER TABLE public."order_items" ADD COLUMN IF NOT EXISTS "variant_label" text;
ALTER TABLE public."order_items" ADD COLUMN IF NOT EXISTS "item_status" text DEFAULT 'disponivel'::text NOT NULL;
ALTER TABLE public."order_items" ADD COLUMN IF NOT EXISTS "item_notes" text;
ALTER TABLE public."order_items" ADD COLUMN IF NOT EXISTS "status_updated_at" timestamp with time zone;
ALTER TABLE public."order_items" ADD COLUMN IF NOT EXISTS "status_updated_by" uuid;
ALTER TABLE public."order_items" ADD COLUMN IF NOT EXISTS "trier_product_id" text;
ALTER TABLE public."order_items" ADD COLUMN IF NOT EXISTS "trier_item_sent" boolean DEFAULT false NOT NULL;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "customer_address" text;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "delivery_method" text DEFAULT 'pickup'::text NOT NULL;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "total" numeric(10,2) DEFAULT 0 NOT NULL;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "status" text DEFAULT 'novo'::text NOT NULL;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "notes" text;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "trier_sent" boolean DEFAULT false NOT NULL;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "trier_sent_at" timestamp with time zone;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "trier_status" text;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "trier_status_code" integer;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "trier_numero_nota" text;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "trier_last_status_check_at" timestamp with time zone;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "trier_error_message" text;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "customer_email" text;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "customer_cpf" text;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "subtotal" numeric DEFAULT 0 NOT NULL;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "discount" numeric DEFAULT 0 NOT NULL;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "delivery_type" text DEFAULT 'pickup'::text NOT NULL;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "delivery_cep" text;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "delivery_street" text;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "delivery_number" text;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "delivery_complement" text;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "delivery_neighborhood" text;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "delivery_city" text;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "delivery_state" text;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "delivery_reference" text;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "delivery_fee" numeric DEFAULT 0 NOT NULL;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "payment_gateway" text;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "payment_method" text;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "order_status" text DEFAULT 'aguardando_pagamento'::text NOT NULL;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "mercado_pago_preference_id" text;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "mercado_pago_payment_id" text;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "mercado_pago_order_id" text;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "mercado_pago_checkout_url" text;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "external_reference" text;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "paid_at" timestamp with time zone;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "cancelled_at" timestamp with time zone;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "fulfillment_status" text DEFAULT 'unfulfilled'::text NOT NULL;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "delivery_status" text DEFAULT 'pending'::text NOT NULL;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "sales_channel" text DEFAULT 'site'::text NOT NULL;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "trier_order_id" text;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "trier_sale_id" text;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "trier_attempts" integer DEFAULT 0 NOT NULL;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "trier_payload_hash" text;
ALTER TABLE public."orders" ADD COLUMN IF NOT EXISTS "trier_last_error" text;
ALTER TABLE public."payment_errors" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."payment_errors" ADD COLUMN IF NOT EXISTS "stage" text NOT NULL;
ALTER TABLE public."payment_errors" ADD COLUMN IF NOT EXISTS "error_code" text;
ALTER TABLE public."payment_errors" ADD COLUMN IF NOT EXISTS "message" text;
ALTER TABLE public."payment_errors" ADD COLUMN IF NOT EXISTS "mp_error" jsonb;
ALTER TABLE public."payment_errors" ADD COLUMN IF NOT EXISTS "supabase_error" jsonb;
ALTER TABLE public."payment_errors" ADD COLUMN IF NOT EXISTS "payload_summary" jsonb;
ALTER TABLE public."payment_errors" ADD COLUMN IF NOT EXISTS "http_status" integer;
ALTER TABLE public."payment_errors" ADD COLUMN IF NOT EXISTS "user_id" uuid;
ALTER TABLE public."payment_errors" ADD COLUMN IF NOT EXISTS "user_email" text;
ALTER TABLE public."payment_events" ADD COLUMN IF NOT EXISTS "gateway" text DEFAULT 'mercado_pago'::text NOT NULL;
ALTER TABLE public."payment_events" ADD COLUMN IF NOT EXISTS "event_type" text;
ALTER TABLE public."payment_events" ADD COLUMN IF NOT EXISTS "external_id" text NOT NULL;
ALTER TABLE public."payment_events" ADD COLUMN IF NOT EXISTS "payload" jsonb;
ALTER TABLE public."payment_events" ADD COLUMN IF NOT EXISTS "processed" boolean DEFAULT false NOT NULL;
ALTER TABLE public."payment_events" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."prescriptions" ADD COLUMN IF NOT EXISTS "notes" text;
ALTER TABLE public."prescriptions" ADD COLUMN IF NOT EXISTS "file_url" text;
ALTER TABLE public."prescriptions" ADD COLUMN IF NOT EXISTS "status" text DEFAULT 'recebida'::text NOT NULL;
ALTER TABLE public."prescriptions" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."prescriptions" ADD COLUMN IF NOT EXISTS "internal_notes" text;
ALTER TABLE public."prescriptions" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."prescriptions" ADD COLUMN IF NOT EXISTS "approved_at" timestamp with time zone;
ALTER TABLE public."product_related" ADD COLUMN IF NOT EXISTS "position" integer DEFAULT 0 NOT NULL;
ALTER TABLE public."product_related" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."product_taxonomy" ADD COLUMN IF NOT EXISTS "is_primary" boolean DEFAULT false NOT NULL;
ALTER TABLE public."product_taxonomy" ADD COLUMN IF NOT EXISTS "is_manual" boolean DEFAULT false NOT NULL;
ALTER TABLE public."product_taxonomy" ADD COLUMN IF NOT EXISTS "source" text DEFAULT 'manual'::text NOT NULL;
ALTER TABLE public."product_taxonomy" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."product_taxonomy" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."product_variants" ADD COLUMN IF NOT EXISTS "trier_product_id" text;
ALTER TABLE public."product_variants" ADD COLUMN IF NOT EXISTS "barcode" text;
ALTER TABLE public."product_variants" ADD COLUMN IF NOT EXISTS "sku" text;
ALTER TABLE public."product_variants" ADD COLUMN IF NOT EXISTS "variation_type" text DEFAULT 'tamanho'::text NOT NULL;
ALTER TABLE public."product_variants" ADD COLUMN IF NOT EXISTS "variation_value" text NOT NULL;
ALTER TABLE public."product_variants" ADD COLUMN IF NOT EXISTS "name" text;
ALTER TABLE public."product_variants" ADD COLUMN IF NOT EXISTS "price" numeric(10,2);
ALTER TABLE public."product_variants" ADD COLUMN IF NOT EXISTS "promo_price" numeric(10,2);
ALTER TABLE public."product_variants" ADD COLUMN IF NOT EXISTS "stock" integer DEFAULT 0 NOT NULL;
ALTER TABLE public."product_variants" ADD COLUMN IF NOT EXISTS "image_url" text;
ALTER TABLE public."product_variants" ADD COLUMN IF NOT EXISTS "position" integer DEFAULT 0 NOT NULL;
ALTER TABLE public."product_variants" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."product_variants" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "price" numeric(10,2) DEFAULT 0 NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "promo_price" numeric(10,2);
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "image_url" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "manufacturer" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "active_ingredient" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "stock" integer DEFAULT 0 NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "featured" boolean DEFAULT false NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "on_sale" boolean DEFAULT false NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "requires_prescription" boolean DEFAULT false NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "controlled" boolean DEFAULT false NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "tarja" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "shelves" text[] DEFAULT '{}'::text[] NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "short_description" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "sku" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "barcode" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "gallery_images" text[] DEFAULT '{}'::text[] NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "promotion_start" timestamp with time zone;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "promotion_end" timestamp with time zone;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "minimum_stock" integer DEFAULT 5 NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "product_badge" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "custom_warning" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "seo_title" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "seo_description" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "seo_keywords" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "discount_percentage" integer GENERATED ALWAYS AS (
CASE
    WHEN ((price > (0)::numeric) AND (promo_price IS NOT NULL) AND (promo_price < price)) THEN (round((((1)::numeric - (promo_price / price)) * (100)::numeric)))::integer
    ELSE 0
END) STORED;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "trier_product_id" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "ecommerce_name" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "laboratory_code" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "laboratory" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "group_code" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "group_name" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "category_external_id" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "category_name" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "department_external_id" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "department_name" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "active_ingredient_code" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "ecommerce_price" numeric;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "stock_quantity" integer;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "ecommerce_stock_quantity" integer;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "is_active" boolean;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "ecommerce_enabled" boolean DEFAULT false;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "max_discount_percentage" numeric;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "sale_observation" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "medicine_list_type" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "tags" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "cart_quantity_limit" integer;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "last_synced_at" timestamp with time zone;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "trier_barcode" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "sync_with_trier" boolean DEFAULT true NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "lock_manual_price" boolean DEFAULT false NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "lock_manual_stock" boolean DEFAULT false NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "source" text DEFAULT 'manual'::text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "last_trier_sync_at" timestamp with time zone;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "pix_discount_percentage" numeric;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "manual_override" boolean DEFAULT false NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "manual_image" boolean DEFAULT false NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "manual_description" boolean DEFAULT false NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "manual_category" boolean DEFAULT false NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "manual_active" boolean DEFAULT false NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "manual_barcode" boolean DEFAULT false NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "manual_name" boolean DEFAULT false NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "manual_seo" boolean DEFAULT false NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "manual_shelves" boolean DEFAULT false NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "trier_stock_quantity" integer;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "last_stock_sync_at" timestamp with time zone;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "manual_disabled" boolean DEFAULT false NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "trier_active" boolean;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "mapping_status" text DEFAULT 'unknown'::text NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "needs_review" boolean DEFAULT false NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "price_origin" text DEFAULT 'manual'::text NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "stock_origin" text DEFAULT 'manual'::text NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "has_variants" boolean DEFAULT false NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "variation_type" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "bestseller_rank" integer;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "is_generic" boolean DEFAULT false NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "commercial_tags" text[] DEFAULT '{}'::text[] NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "show_in_menu" boolean DEFAULT true NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "show_in_filters" boolean DEFAULT true NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "price_base" numeric;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "site_price" numeric;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "whatsapp_price" numeric;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "site_promo_price" numeric;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "whatsapp_promo_price" numeric;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "use_channel_pricing" boolean DEFAULT false NOT NULL;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "channel_price_notes" text;
ALTER TABLE public."products" ADD COLUMN IF NOT EXISTS "publish_even_incomplete" boolean DEFAULT false NOT NULL;
ALTER TABLE public."profiles" ADD COLUMN IF NOT EXISTS "cpf" text;
ALTER TABLE public."profiles" ADD COLUMN IF NOT EXISTS "email" text;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "position" integer DEFAULT 0 NOT NULL;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "variant" text DEFAULT 'default'::text NOT NULL;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "title" text;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "subtitle" text;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "badge_text" text;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "old_price" numeric;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "new_price" numeric;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "price_suffix" text;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "image_url" text;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "cta_text" text;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "cta_url" text;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "image_mode" text DEFAULT 'product'::text NOT NULL;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "block_type" text DEFAULT 'card_medio'::text NOT NULL;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "image_position" text DEFAULT 'direita'::text NOT NULL;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "image_size" text DEFAULT 'medio'::text NOT NULL;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "show_text" boolean DEFAULT true NOT NULL;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "show_price" boolean DEFAULT true NOT NULL;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "show_cta" boolean DEFAULT true NOT NULL;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "bg_color" text DEFAULT 'azul_claro'::text NOT NULL;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "bg_custom" text;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "cta_color" text DEFAULT 'vermelho'::text NOT NULL;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "animation_type" text DEFAULT 'float'::text;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "theme_key" text DEFAULT 'default'::text;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "background_image_url" text;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "background_intensity" text DEFAULT 'soft'::text;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "decoration_enabled" boolean DEFAULT true;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "custom_background_color" text;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "custom_cta_color" text;
ALTER TABLE public."promo_banner_blocks" ADD COLUMN IF NOT EXISTS "custom_badge_color" text;
ALTER TABLE public."refund_items" ADD COLUMN IF NOT EXISTS "quantity" integer DEFAULT 1 NOT NULL;
ALTER TABLE public."refund_items" ADD COLUMN IF NOT EXISTS "amount" numeric(12,2) DEFAULT 0 NOT NULL;
ALTER TABLE public."refund_items" ADD COLUMN IF NOT EXISTS "reason" text;
ALTER TABLE public."refund_items" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."refund_requests" ADD COLUMN IF NOT EXISTS "payment_id" text;
ALTER TABLE public."refund_requests" ADD COLUMN IF NOT EXISTS "requested_by" uuid;
ALTER TABLE public."refund_requests" ADD COLUMN IF NOT EXISTS "reason" text;
ALTER TABLE public."refund_requests" ADD COLUMN IF NOT EXISTS "type" text DEFAULT 'partial'::text NOT NULL;
ALTER TABLE public."refund_requests" ADD COLUMN IF NOT EXISTS "amount" numeric(12,2);
ALTER TABLE public."refund_requests" ADD COLUMN IF NOT EXISTS "status" text DEFAULT 'pending'::text NOT NULL;
ALTER TABLE public."refund_requests" ADD COLUMN IF NOT EXISTS "mercado_pago_refund_id" text;
ALTER TABLE public."refund_requests" ADD COLUMN IF NOT EXISTS "idempotency_key" text;
ALTER TABLE public."refund_requests" ADD COLUMN IF NOT EXISTS "error_message" text;
ALTER TABLE public."refund_requests" ADD COLUMN IF NOT EXISTS "processed_by" uuid;
ALTER TABLE public."refund_requests" ADD COLUMN IF NOT EXISTS "processed_at" timestamp with time zone;
ALTER TABLE public."refund_requests" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."refund_requests" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."stock_movements" ADD COLUMN IF NOT EXISTS "type" text NOT NULL;
ALTER TABLE public."stock_movements" ADD COLUMN IF NOT EXISTS "quantity" numeric NOT NULL;
ALTER TABLE public."stock_movements" ADD COLUMN IF NOT EXISTS "reason" text;
ALTER TABLE public."stock_movements" ADD COLUMN IF NOT EXISTS "source" text;
ALTER TABLE public."stock_movements" ADD COLUMN IF NOT EXISTS "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE public."stock_movements" ADD COLUMN IF NOT EXISTS "created_by" uuid;
ALTER TABLE public."stock_movements" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."subcategories" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE public."subcategories" ADD COLUMN IF NOT EXISTS "icon" text;
ALTER TABLE public."subcategories" ADD COLUMN IF NOT EXISTS "position" integer DEFAULT 0 NOT NULL;
ALTER TABLE public."subcategories" ADD COLUMN IF NOT EXISTS "show_in_menu" boolean DEFAULT true NOT NULL;
ALTER TABLE public."subcategories" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public."subcategories" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;

commit;

