-- Make public catalog and merchandising records explicitly store-owned.
-- Existing rows are assigned to the client-zero store. Public catalog rows
-- remain public by design; tenant filters are mandatory in storefront queries.
-- Authenticated writes receive an additional restrictive organization policy.

begin;

do $catalog_tables$
declare
  table_name text;
  constraint_name text;
begin
  foreach table_name in array array[
    'departments',
    'categories',
    'subcategories',
    'products',
    'product_variants',
    'product_related',
    'product_taxonomy',
    'stock_movements',
    'banners',
    'campaigns',
    'campaign_products',
    'home_layout',
    'home_mosaic_tiles',
    'menu_items',
    'promo_banner_blocks'
  ]
  loop
    if to_regclass(format('public.%I', table_name)) is null then
      raise exception 'required catalog table public.% is missing', table_name;
    end if;

    execute format(
      'alter table public.%I
         add column if not exists organization_id uuid,
         add column if not exists store_id uuid',
      table_name
    );

    execute format(
      'update public.%I
          set organization_id = coalesce(
                organization_id,
                %L::uuid
              ),
              store_id = coalesce(
                store_id,
                %L::uuid
              )
        where organization_id is null or store_id is null',
      table_name,
      '00000000-0000-0000-0000-000000000001',
      '00000000-0000-0000-0000-000000000002'
    );

    execute format(
      'alter table public.%I
         alter column organization_id set not null,
         alter column store_id set not null',
      table_name
    );

    constraint_name := table_name || '_store_same_org_fk';
    if not exists (
      select 1
      from pg_constraint
      where conname = constraint_name
        and conrelid = format('public.%I', table_name)::regclass
    ) then
      execute format(
        'alter table public.%I
           add constraint %I
           foreign key (organization_id, store_id)
           references public.stores (organization_id, id)
           on delete restrict',
        table_name,
        constraint_name
      );
    end if;

    constraint_name := table_name || '_tenant_identity_key';
    if table_name <> 'product_related' and not exists (
      select 1
      from pg_constraint
      where conname = constraint_name
        and conrelid = format('public.%I', table_name)::regclass
    ) then
      execute format(
        'alter table public.%I
           add constraint %I
           unique (organization_id, store_id, id)',
        table_name,
        constraint_name
      );
    end if;

    execute format(
      'drop policy if exists %I on public.%I',
      table_name || '_tenant_insert',
      table_name
    );
    execute format(
      'create policy %I
         on public.%I
         as restrictive
         for insert
         to authenticated
         with check (
           private.has_organization_role(
             organization_id,
             array[''owner'', ''admin'', ''manager'']
           )
         )',
      table_name || '_tenant_insert',
      table_name
    );

    execute format(
      'drop policy if exists %I on public.%I',
      table_name || '_tenant_update',
      table_name
    );
    execute format(
      'create policy %I
         on public.%I
         as restrictive
         for update
         to authenticated
         using (
           private.has_organization_role(
             organization_id,
             array[''owner'', ''admin'', ''manager'']
           )
         )
         with check (
           private.has_organization_role(
             organization_id,
             array[''owner'', ''admin'', ''manager'']
           )
         )',
      table_name || '_tenant_update',
      table_name
    );

    execute format(
      'drop policy if exists %I on public.%I',
      table_name || '_tenant_delete',
      table_name
    );
    execute format(
      'create policy %I
         on public.%I
         as restrictive
         for delete
         to authenticated
         using (
           private.has_organization_role(
             organization_id,
             array[''owner'', ''admin'', ''manager'']
           )
         )',
      table_name || '_tenant_delete',
      table_name
    );
  end loop;
end;
$catalog_tables$;

-- Slugs/section keys are store-local. Remove the single-store constraints
-- generated by Lovable and replace them with tenant-scoped uniqueness.
alter table public.departments drop constraint if exists departments_slug_key;
alter table public.categories drop constraint if exists categories_slug_key;
alter table public.products drop constraint if exists products_slug_key;
alter table public.campaigns drop constraint if exists campaigns_slug_key;
alter table public.home_layout drop constraint if exists home_layout_section_key_key;

create unique index if not exists departments_tenant_slug_uidx
  on public.departments (organization_id, store_id, slug);
create unique index if not exists categories_tenant_slug_uidx
  on public.categories (organization_id, store_id, slug);
create unique index if not exists products_tenant_slug_uidx
  on public.products (organization_id, store_id, slug);
create unique index if not exists campaigns_tenant_slug_uidx
  on public.campaigns (organization_id, store_id, slug);
create unique index if not exists home_layout_tenant_section_key_uidx
  on public.home_layout (organization_id, store_id, section_key);

-- New and changed relationships cannot cross organization/store boundaries.
-- NOT VALID avoids blocking the migration on historical orphans while still
-- enforcing the invariant for every new write. Validation follows after the
-- data-quality cleanup.
do $catalog_relations$
declare
  relation record;
begin
  for relation in
    select *
    from (values
      ('categories', 'department_id', 'departments', 'categories_department_same_tenant_fk'),
      ('subcategories', 'category_id', 'categories', 'subcategories_category_same_tenant_fk'),
      ('products', 'category_id', 'categories', 'products_category_same_tenant_fk'),
      ('products', 'generic_equivalent_id', 'products', 'products_generic_same_tenant_fk'),
      ('product_variants', 'parent_product_id', 'products', 'product_variants_parent_same_tenant_fk'),
      ('product_related', 'product_id', 'products', 'product_related_product_same_tenant_fk'),
      ('product_related', 'related_product_id', 'products', 'product_related_related_same_tenant_fk'),
      ('product_taxonomy', 'product_id', 'products', 'product_taxonomy_product_same_tenant_fk'),
      ('product_taxonomy', 'department_id', 'departments', 'product_taxonomy_department_same_tenant_fk'),
      ('product_taxonomy', 'category_id', 'categories', 'product_taxonomy_category_same_tenant_fk'),
      ('product_taxonomy', 'subcategory_id', 'subcategories', 'product_taxonomy_subcategory_same_tenant_fk'),
      ('stock_movements', 'product_id', 'products', 'stock_movements_product_same_tenant_fk'),
      ('banners', 'linked_campaign_id', 'campaigns', 'banners_campaign_same_tenant_fk'),
      ('banners', 'linked_category_id', 'categories', 'banners_category_same_tenant_fk'),
      ('banners', 'linked_product_id', 'products', 'banners_product_same_tenant_fk'),
      ('campaigns', 'destination_category_id', 'categories', 'campaigns_category_same_tenant_fk'),
      ('campaigns', 'destination_product_id', 'products', 'campaigns_product_same_tenant_fk'),
      ('campaign_products', 'campaign_id', 'campaigns', 'campaign_products_campaign_same_tenant_fk'),
      ('campaign_products', 'product_id', 'products', 'campaign_products_product_same_tenant_fk'),
      ('home_mosaic_tiles', 'campaign_id', 'campaigns', 'home_mosaic_campaign_same_tenant_fk'),
      ('home_mosaic_tiles', 'category_id', 'categories', 'home_mosaic_category_same_tenant_fk'),
      ('home_mosaic_tiles', 'product_id', 'products', 'home_mosaic_product_same_tenant_fk'),
      ('menu_items', 'campaign_id', 'campaigns', 'menu_items_campaign_same_tenant_fk'),
      ('menu_items', 'category_id', 'categories', 'menu_items_category_same_tenant_fk'),
      ('menu_items', 'product_id', 'products', 'menu_items_product_same_tenant_fk'),
      ('menu_items', 'parent_id', 'menu_items', 'menu_items_parent_same_tenant_fk')
    ) as relations(child_table, child_column, parent_table, constraint_name)
  loop
    if not exists (
      select 1
      from information_schema.columns
      where table_schema = 'public'
        and table_name = relation.child_table
        and column_name = relation.child_column
    ) then
      raise exception 'required relationship column %.% is missing',
        relation.child_table,
        relation.child_column;
    end if;

    if not exists (
      select 1
      from pg_constraint
      where conname = relation.constraint_name
        and conrelid = format('public.%I', relation.child_table)::regclass
    ) then
      execute format(
        'alter table public.%I
           add constraint %I
           foreign key (organization_id, store_id, %I)
           references public.%I (organization_id, store_id, id)
           not valid',
        relation.child_table,
        relation.constraint_name,
        relation.child_column,
        relation.parent_table
      );
    end if;
  end loop;
end;
$catalog_relations$;

commit;
