import { useState } from "react";
import type { ReactNode } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { toast } from "sonner";
import { CheckCircle2, ClipboardList, PackageCheck, Plus } from "lucide-react";

const statusLabel: Record<string, string> = { draft: "Rascunho", pending: "Pendente", approved: "Aprovado", received: "Recebido", partially_received: "Parcial", cancelled: "Cancelado", checked: "Conferido", posted: "Lançado" };

export default function AdminPurchaseOperations() {
  const { user } = useAuth(); const qc = useQueryClient(); const [openOrder, setOpenOrder] = useState(false); const [openReceipt, setOpenReceipt] = useState(false);
  const { data: tenantId } = useQuery({ queryKey: ["purchase-tenant", user?.id], enabled: !!user?.id, queryFn: async () => (await (supabase as any).from("tenant_memberships").select("tenant_id").eq("user_id", user!.id).limit(1).maybeSingle()).data?.tenant_id });
  const { data: stores = [] } = useQuery({ queryKey: ["purchase-stores", tenantId], enabled: !!tenantId, queryFn: async () => (await (supabase as any).from("stores").select("id,name").eq("tenant_id", tenantId).eq("active", true).order("name")).data || [] });
  const { data: suppliers = [] } = useQuery({ queryKey: ["purchase-suppliers", tenantId], enabled: !!tenantId, queryFn: async () => (await (supabase as any).from("suppliers").select("id,legal_name,trade_name").eq("tenant_id", tenantId).eq("active", true).order("legal_name")).data || [] });
  const { data: orders = [] } = useQuery({ queryKey: ["purchase-orders", tenantId], enabled: !!tenantId, queryFn: async () => { const r = await (supabase as any).from("purchase_orders").select("*, suppliers(legal_name,trade_name), stores(name)").eq("tenant_id", tenantId).order("created_at", { ascending: false }); return r.data || []; } });
  const { data: receipts = [] } = useQuery({ queryKey: ["goods-receipts", tenantId], enabled: !!tenantId, queryFn: async () => { const r = await (supabase as any).from("goods_receipts").select("*, suppliers(legal_name,trade_name), stores(name)").eq("tenant_id", tenantId).order("received_at", { ascending: false }); return r.data || []; } });
  const refresh = () => { qc.invalidateQueries({ queryKey: ["purchase-orders"] }); qc.invalidateQueries({ queryKey: ["goods-receipts"] }); };
  const approve = async (id: string) => { const { error } = await (supabase as any).rpc("approve_purchase_order", { _order_id: id }); if (error) toast.error(error.message); else { toast.success("Pedido aprovado."); refresh(); } };
  const post = async (id: string) => { const { error } = await (supabase as any).rpc("post_goods_receipt", { _receipt_id: id }); if (error) toast.error(error.message); else { toast.success("Entrada lançada no estoque."); refresh(); } };
  return <div className="p-6 space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-extrabold">Compras e recebimentos</h1><p className="text-sm text-muted-foreground mt-1">Fluxo próprio do ERP: pedido, aprovação, conferência e entrada no estoque.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => setOpenReceipt(true)}><PackageCheck className="h-4 w-4 mr-2" />Nova entrada</Button><Button onClick={() => setOpenOrder(true)}><Plus className="h-4 w-4 mr-2" />Novo pedido</Button></div></div>
    <Tabs defaultValue="orders"><TabsList><TabsTrigger value="orders"><ClipboardList className="h-4 w-4 mr-2" />Pedidos de compra ({orders.length})</TabsTrigger><TabsTrigger value="receipts"><PackageCheck className="h-4 w-4 mr-2" />Recebimentos ({receipts.length})</TabsTrigger></TabsList>
      <TabsContent value="orders"><Table><thead><tr><th>Pedido</th><th>Fornecedor</th><th>Loja</th><th>Total</th><th>Status</th><th>Ação</th></tr></thead><tbody>{orders.map((o: any) => <tr key={o.id}><td>#{o.number}</td><td>{o.suppliers?.trade_name || o.suppliers?.legal_name || "—"}</td><td>{o.stores?.name || "—"}</td><td>R$ {Number(o.total || 0).toFixed(2)}</td><td><Badge>{statusLabel[o.status] || o.status}</Badge></td><td>{["draft", "pending"].includes(o.status) && <Button size="sm" variant="outline" onClick={() => approve(o.id)}><CheckCircle2 className="h-4 w-4 mr-1" />Aprovar</Button>}</td></tr>)}{!orders.length && <Empty />}</tbody></Table></TabsContent>
      <TabsContent value="receipts"><Table><thead><tr><th>Recebimento</th><th>Fornecedor</th><th>Nota fiscal</th><th>Total</th><th>Status</th><th>Ação</th></tr></thead><tbody>{receipts.map((r: any) => <tr key={r.id}><td>{new Date(r.received_at).toLocaleDateString("pt-BR")}</td><td>{r.suppliers?.trade_name || r.suppliers?.legal_name || "—"}</td><td>{r.supplier_invoice_number || "—"}</td><td>R$ {Number(r.total_cost || 0).toFixed(2)}</td><td><Badge>{statusLabel[r.status] || r.status}</Badge></td><td>{["draft", "checked"].includes(r.status) && <Button size="sm" onClick={() => post(r.id)}>Lançar no estoque</Button>}</td></tr>)}{!receipts.length && <Empty />}</tbody></Table></TabsContent>
    </Tabs><OrderDialog open={openOrder} onOpenChange={setOpenOrder} tenantId={tenantId} stores={stores} suppliers={suppliers} onSaved={refresh} /><ReceiptDialog open={openReceipt} onOpenChange={setOpenReceipt} tenantId={tenantId} stores={stores} suppliers={suppliers} orders={orders} onSaved={refresh} /></div>;
}

function Table({ children }: { children: ReactNode }) { return <div className="bg-card border rounded-xl overflow-x-auto"><table className="w-full text-sm"><thead className="bg-secondary text-left">{children}</thead></table></div>; }
function Empty() { return <tr><td colSpan={6} className="p-10 text-center text-muted-foreground">Nenhum registro cadastrado.</td></tr>; }
function Field({ label, value, onChange, type = "text" }: any) { return <div className="space-y-1"><Label>{label}</Label><Input type={type} value={value} onChange={(e) => onChange(e.target.value)} /></div>; }
function SelectField({ label, value, onChange, options }: any) { return <div className="space-y-1"><Label>{label}</Label><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={value} onChange={(e) => onChange(e.target.value)}><option value="">Selecione...</option>{options.map((o: any) => <option key={o.id} value={o.id}>{o.name || o.trade_name || o.legal_name}</option>)}</select></div>; }

function OrderDialog({ open, onOpenChange, tenantId, stores, suppliers, onSaved }: any) { const [store, setStore] = useState(""); const [supplier, setSupplier] = useState(""); const [product, setProduct] = useState(""); const [qty, setQty] = useState("1"); const [cost, setCost] = useState(""); const [saving, setSaving] = useState(false); const save = async () => { if (!tenantId || !store || !supplier || !product || Number(qty) <= 0) return toast.error("Preencha loja, fornecedor, produto e quantidade."); setSaving(true); const { data: order, error } = await (supabase as any).from("purchase_orders").insert({ tenant_id: tenantId, store_id: store, supplier_id: supplier, number: Date.now(), status: "draft", subtotal: Number(qty) * Number(cost || 0), total: Number(qty) * Number(cost || 0) }).select().single(); if (!error) { const r = await (supabase as any).from("purchase_order_items").insert({ purchase_order_id: order.id, product_id: product, quantity_ordered: Number(qty), unit_cost: Number(cost || 0), line_total: Number(qty) * Number(cost || 0) }); if (r.error) toast.error(r.error.message); else { toast.success("Pedido criado."); onOpenChange(false); onSaved(); } } else toast.error(error.message); setSaving(false); }; return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Novo pedido de compra</DialogTitle></DialogHeader><div className="grid gap-3"><SelectField label="Fornecedor" value={supplier} onChange={setSupplier} options={suppliers} /><SelectField label="Loja de destino" value={store} onChange={setStore} options={stores} /><Field label="ID do produto" value={product} onChange={setProduct} /><div className="grid grid-cols-2 gap-3"><Field label="Quantidade" type="number" value={qty} onChange={setQty} /><Field label="Custo unitário" type="number" value={cost} onChange={setCost} /></div></div><DialogFooter><Button onClick={save} disabled={saving}>{saving ? "Salvando..." : "Criar pedido"}</Button></DialogFooter></DialogContent></Dialog>; }

function ReceiptDialog({ open, onOpenChange, tenantId, stores, suppliers, orders, onSaved }: any) { const [store, setStore] = useState(""); const [supplier, setSupplier] = useState(""); const [order, setOrder] = useState(""); const [product, setProduct] = useState(""); const [qty, setQty] = useState("1"); const [cost, setCost] = useState(""); const [batch, setBatch] = useState(""); const [expiry, setExpiry] = useState(""); const [saving, setSaving] = useState(false); const save = async () => { if (!tenantId || !store || !supplier || !product || Number(qty) <= 0) return toast.error("Preencha loja, fornecedor, produto e quantidade."); setSaving(true); const { data: receipt, error } = await (supabase as any).from("goods_receipts").insert({ tenant_id: tenantId, store_id: store, supplier_id: supplier, purchase_order_id: order || null, status: "draft", total_cost: Number(qty) * Number(cost || 0) }).select().single(); if (!error) { const r = await (supabase as any).from("goods_receipt_items").insert({ goods_receipt_id: receipt.id, product_id: product, quantity: Number(qty), unit_cost: Number(cost || 0), batch_number: batch || null, expiry_date: expiry || null }); if (r.error) toast.error(r.error.message); else { toast.success("Recebimento criado. Confira e lance no estoque."); onOpenChange(false); onSaved(); } } else toast.error(error.message); setSaving(false); }; return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Nova entrada de mercadorias</DialogTitle></DialogHeader><div className="grid gap-3"><SelectField label="Fornecedor" value={supplier} onChange={setSupplier} options={suppliers} /><SelectField label="Loja de destino" value={store} onChange={setStore} options={stores} /><SelectField label="Pedido relacionado (opcional)" value={order} onChange={setOrder} options={orders.map((o: any) => ({ id: o.id, name: `#${o.number}` }))} /><div className="grid grid-cols-2 gap-3"><Field label="ID do produto" value={product} onChange={setProduct} /><Field label="Quantidade" type="number" value={qty} onChange={setQty} /></div><div className="grid grid-cols-2 gap-3"><Field label="Custo unitário" type="number" value={cost} onChange={setCost} /><Field label="Lote" value={batch} onChange={setBatch} /></div><Field label="Validade" type="date" value={expiry} onChange={setExpiry} /></div><DialogFooter><Button onClick={save} disabled={saving}>{saving ? "Salvando..." : "Criar recebimento"}</Button></DialogFooter></DialogContent></Dialog>; }
